### ISSUE TITLE
Style wrapper and app-container with Bootstrap

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/baat-cheet#141]
Style the division with `wrapper` class and the division with `app-container` class using Bootstrap.

**Comment by igu** [comment]
you can assign this issue to me?

**Comment by LalitNM** [comment]
Go ahead @igu.

**Comment by igu** [comment]
@LalitNM can you talk more about this problem?

**Comment by LalitNM** [comment]
@igu, at present there is so much css styling for just `.app-container`. But, this can be easily styled using Bootstrap's `.container`. You are supposed  to achieve this.

And `.wrapper` is used with `.fadeIn()` and `.fadeOut()`, it will be appreciated if you can give it a more meaningful class(or an id), or even completely remove this and make just one element with class `container` and some id.

**Comment by LalitNM** [comment]
Any update @igu?

**Comment by igu** [comment]
Sorry, i don't can help now, issues college are take my all time
