### ISSUE TITLE
Clean imports

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/baat-cheet#142]
Clean the files [head_imports](https://github.com/KamandPrompt/baat-cheet/blob/master/views/head_imports.ejs) and [footer_imports](https://github.com/KamandPrompt/baat-cheet/blob/master/views/footer_imports.ejs).

Currently there are so many cdns, remove unnecessary ones and arrange all CSS cdns in head_imports and all JS cdns in footer_imports.

If you want to discuss something, then chat [here](https://gitter.im/Baat-Cheet-IIT/issues).

**Comment by Jeconias** [comment]
You can assign it to me?

**Comment by LalitNM** [comment]
Done @Jeconias. Come back with a pull request within 2 days.

**Comment by Jeconias** [comment]
@LalitNM, Done.
