### ISSUE TITLE
Shift emoji ids and names to a json file

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/baat-cheet#143]
At present there are two list of emoji ids and their CLDR code names. Your job is to make a json file and shift all these ids ans names in that file. Also make API to read from that file.

For discussion chat [here](https://gitter.im/Baat-Cheet-IIT/issues).

**Comment by Ezio-Sarthak** [comment]
Could I work on this issue ? It seems new and interesting to learn !

**Comment by LalitNM** [comment]
Sure @Ezio-Sarthak go ahead.

**Comment by Ezio-Sarthak** [comment]
@kpbot claim

**Comment by LalitNM** [comment]
Fixed in #147
