### ISSUE TITLE
When a new room is created, the text area goes hidden for users who don't join the room.

### ISSUE THREAD

**Issue by HitRam** [KamandPrompt/baat-cheet#17]
<img width="1076" alt="screen shot 2017-02-11 at 2 51 00 pm" src="https://cloud.githubusercontent.com/assets/19632768/22852771/925dab86-f069-11e6-87b1-e2390c3581aa.png">

**Comment by abhigyank** [comment]
I'll look into it.

**Comment by abhigyank** [comment]
Fixed in commit cd54256  .
