### ISSUE TITLE
Add an About Section

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/baat-cheet#170]
**Is your feature request related to a problem? Please describe.**
At present, nobody gets to know who made the application and who is responsible for maintenance.

**Describe the solution you'd like**
Adding a section on main landing page that says that the application has been developed and maintained by IIT Mandi or KamandPrompt.

**Comment by GAURAV1-ui** [comment]
I would love to contribute.

**Comment by LalitNM** [comment]
Glad to know this. You can go ahead. See you with a Pull Request. You can self assign this issue by commenting `@kpbot claim` here.

**Comment by GAURAV1-ui** [comment]
@kpbot claim

**Comment by LalitNM** [comment]
Looks like @kpbot isn't working. I'll look into it. For now, let me assign this issue to you so that you can start working on it.

**Comment by mostlyaman** [comment]
Hi, I have added a minimal about section on the landing page. Let me know of any required changes.
