### ISSUE TITLE
Show notification if new message comes to any room 

### ISSUE THREAD

**Issue by HitRam** [KamandPrompt/baat-cheet#24]

**Comment by SubhamKarmakar24** [comment]
@HitRam Can I take up this issue??

**Comment by MonarthS** [comment]
@LalitNM I can add this feature.

**Comment by LalitNM** [comment]
Go ahead @MonarthS, I have asigned you this issue.

**Comment by MonarthS** [comment]
Do you want it like this:
```
user_name@Room
Message
```
![image](https://user-images.githubusercontent.com/40236229/95067044-db07c700-0720-11eb-821c-7396977846d1.png)
