### ISSUE TITLE
username becomes undefined sometimes.

### ISSUE THREAD

**Issue by HitRam** [KamandPrompt/baat-cheet#25]
<img width="771" alt="screen shot 2017-02-18 at 7 31 54 pm" src="https://cloud.githubusercontent.com/assets/19632768/23093732/0294976e-f611-11e6-8f15-e1e757c77bb0.png">

**Comment by abhigyank** [comment]
Sometimes as in?

**Comment by HitRam** [comment]
couldn't figure it out!

**Comment by abhigyank** [comment]
What if the user chose the username as "undefined" in this case? I don't think this is a legitimate issue.

**Comment by sahilarora535** [comment]
@abhigyank Even I have faced this issue. Please consider looking into it.

**Comment by abhigyank** [comment]
@sahilarora535 Can you specify how to replicate?

**Comment by sahilarora535** [comment]
There were no exact steps. All I did was joined a lot of times, and entered some name. The name was shown undefined. It was random. I don't exactly know how to replicate it.

**Comment by sahilarora535** [comment]
@abhigyank solved? :open_mouth:

**Comment by abhigyank** [comment]
@sahilarora535 There was no reproduction.
