### ISSUE TITLE
Improve position and CSS of New Room button

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/baat-cheet#30]
Redesign the New Room button and put it in a better place.

**Comment by Deepshikha99** [comment]
I claim this issue

**Comment by abhigyank** [comment]
@Deepshikha99 good job on working on this. However don't you think the dropdown menu is a bit redundant for just one option. Do you think instead if we put a '+' sign button it'd look simple and good? You can probably use plus sign icon from the web or an image too. 
Can you do this and update the PR?

**Comment by abhigyank** [comment]
Closed in #35 .
