### ISSUE TITLE
Improve the message design

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/baat-cheet#52]
A message sent/received right now is has very big height (probably due to it being a <p> tag ). The message box height should be in much smaller. And the sender name should be prominent, probably darker.

**Comment by LalitNM** [comment]
@kpbot claim

**Comment by LalitNM** [comment]
Can we add timestamp to every message?

**Comment by abhigyank** [comment]
Definitely that would be great!

**Comment by LalitNM** [comment]
How about this?
![BaatCheet](https://user-images.githubusercontent.com/63332774/87278539-4ff0a980-c502-11ea-85cd-4bac1c7acf55.png)

**Comment by abhigyank** [comment]
Looks much better than now !
Do you think  we should remove the name from the sent message? Because that's kinda obvious it will be me right?
Also the name in the received message (blue one) could be more  prominent, like darker probably 🤔

**Comment by LalitNM** [comment]
now?
![baatcheet](https://user-images.githubusercontent.com/63332774/87279729-eaef8080-c50e-11ea-8820-7a920007b55d.png)

**Comment by abhigyank** [comment]
Looks great !
