### ISSUE TITLE
Style leftbar with bootstrap

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/baat-cheet#92]
At present, the leftbar is styled by custom classes, remove these custom classes and add Bootstrap classes there.

**Comment by Aditya-ds-1806** [comment]
I would like to do this. Can u assign it to me?

**Comment by LalitNM** [comment]
@Aditya-ds-1806 go ahead.

**Comment by Aditya-ds-1806** [comment]
Hey I made a PR please review.
